### ISSUE TITLE
Write output to file rather than keep in buffer

### ISSUE THREAD

**Issue by tollmanz** [Automattic/WordPress-CLI-Exporter#2]
I was never able to successfully export any data using this script due to memory exhausted errors. I allocated as much as 2GB of memory to the script, which allowed the script to run for about 18-20 minutes before failing due to memory exhaustion errors. I wonder if it might be reasonable to change how the output is handled. Rather than store the output in the buffer, it might be worth writing to a file more frequently (this could be done in numerous different ways) in order to reduce the amount of memory needed for the script. It might be worth arbitrarily writing to the file after X number of posts and then freeing up that memory. This would hopefully reduce the amount of memory exhaustion errors.

**Comment by danielbachhuber** [comment]
Fixed by Mo's pull request
